version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: lint
      #     command: npm run lint
      - run:
          name: test
          command: npm test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build